export const GENRE_CLUSTERS = {
  'RPG/ARPG': ['rpg', 'action rpg', 'arpg', 'jrpg', 'crpg', 'mmorpg', 'dungeon crawler',
                '角色扮演', '动作角色扮演', '动作rpg', '日式角色扮演', '类魂'],
  'FPS/射击': ['fps', 'shooter', 'first-person', 'hero shooter', 'tactical shooter',
               '射击', '第一人称', '第一人称射击', '第三人称射击', '射击游戏'],
  '策略/模拟': ['strategy', 'simulation', 'rts', 'turn-based', 'turn based', '4x', 'grand strategy',
                'tower defense', 'moba', 'life sim', 'dating sim', 'farming sim', 'choices matter',
                '策略', '模拟', '回合制', '即时战略', '回合制策略', '塔防', '恋爱模拟'],
  '冒险/叙事': ['adventure', 'narrative', 'visual novel', 'interactive fiction', 'walking simulator',
                'point & click', 'open world', 'open-world', 'sci-fi', 'atmospheric',
                '冒险', '叙事', '剧情', '开放世界', '视觉小说', '探索', '科幻', '互动小说'],
  '恐怖/生存': ['horror', 'survival', 'zombies', 'psychological horror', 'lovecraftian',
                'post-apocalyptic', 'post apocalyptic',
                '恐怖', '生存', '僵尸', '末日', '后末日', '心理恐怖'],
  '动作/格斗': ['action', 'fighting', 'beat \'em up', 'hack and slash', 'stealth', 'metroidvania',
                'bullet hell', 'souls-like', 'soulslike', 'platformer',
                '动作', '格斗', '清版', '类银河战士恶魔城', '平台'],
  '独立/创意': ['indie', 'roguelike', 'roguelite', 'rogue-like', 'rogue-lite',
                '独立', '肉鸽', '类rogue', '像素', '创意'],
  '沙盒/建造': ['sandbox', 'building', 'crafting', 'base building', 'city builder',
                'colony sim', 'voxel', 'automation', 'open world survival craft',
                '沙盒', '建造', '城市建设', '殖民模拟', '自动化'],
  '竞速/体育': ['racing', 'sports', 'vehicular combat',
                '竞速', '体育', '赛车', '驾驶', '足球', '篮球'],
  '休闲/解谜': ['casual', 'puzzle', 'card game', 'board game', 'hidden object', 'idle', 'clicker',
                'match 3', 'word game', 'rhythm',
                '休闲', '解谜', '卡牌', '棋盘', '消除', '三消', '益智', '音乐'],
};

export const GENRE_TO_CLUSTER = {};
for (const [cluster, keywords] of Object.entries(GENRE_CLUSTERS)) {
  for (const kw of keywords) {
    GENRE_TO_CLUSTER[kw.toLowerCase()] = cluster;
  }
}

export const SERIES_PATTERNS = [
  /(Civilization\s*\d*)/i,
  /(Final Fantasy\s*\d*)/i,
  /(Call of Duty.*)/i,
  /(Assassin's Creed.*)/i,
  /(Total War.*)/i,
  /(The Elder Scrolls.*)/i,
  /(Far Cry\s*\d*)/i,
  /(Borderlands\s*\d*)/i,
  /(Dark Souls\s*\d*)/i,
  /(Resident Evil\s*\d*)/i,
  /(Need for Speed.*)/i,
  /(Fallout\s*\d*)/i,
  /(Mass Effect\s*\d*)/i,
  /(Dragon Age\s*\d*)/i,
  /(BioShock\s*\d*)/i,
  /(Portal\s*\d*)/i,
  /(Half-Life\s*\d*)/i,
  /(Wolfenstein\s*\d*)/i,
  /(Doom\s*\d*)/i,
  /(Hitman\s*\d*)/i,
  /(Tomb Raider.*)/i,
  /(Uncharted.*)/i,
  /(God of War.*)/i,
  /(Halo\s*\d*)/i,
  /(Gears of War.*)/i,
  /(Forza.*)/i,
  /(FIFA\s*\d*)/i,
  /(NBA 2K\d*)/i,
  /(Madden\s*\d*)/i,
  /(Monster Hunter.*)/i,
  /(Persona\s*\d*)/i,
  /(Yakuza.*)/i,
  /(Like a Dragon.*)/i,
  /(XCOM\s*\d*)/i,
  /(StarCraft\s*\d*)/i,
  /(Warcraft\s*\d*)/i,
  /(Diablo\s*\d*)/i,
  /(Overwatch\s*\d*)/i,
  /(Rainbow Six.*)/i,
  /(Ghost Recon.*)/i,
  /(Splinter Cell.*)/i,
  /(Prince of Persia.*)/i,
  /(Silent Hill.*)/i,
  /(Metal Gear.*)/i,
  /(Kingdom Hearts.*)/i,
  /(Street Fighter.*)/i,
  /(Tekken\s*\d*)/i,
  /(Mortal Kombat\s*\d*)/i,
  /(Dead or Alive.*)/i,
  /(Soulcalibur.*)/i,
  /(Sonic\s*.*)/i,
  /(Kirby.*)/i,
  /(Zelda.*)/i,
  /(Mario\s*.*)/i,
  /(Pokemon.*)/i,
  /(Dragon Quest.*)/i,
  /(NieR.*)/i,
  /(Bayonetta.*)/i,
  /(Devil May Cry.*)/i,
  /(Dead Space.*)/i,
  /(System Shock.*)/i,
  /(Disco Elysium.*)/i,
  /(Baldur's Gate.*)/i,
  /(Pillars of Eternity.*)/i,
  /(Divinity.*)/i,
  /(Warhammer.*)/i,
  /(Star Wars.*)/i,
  /(Alien\s*.*)/i,
  /(Predator.*)/i,
];
